censocademico/CargaAcademica.WebAdmin/Controllers/CensoMasterController.cs
using CargaAcademica.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargaAcademica.WebAdmin.Controllers
{
    public class CensoMasterController : Controller
    {

        CensoMaestroBL _CensosMasterBL;

        PeriodoBL _PeriodoBL;

        AlumnoBL _AlumnoBL;

        public CensoMasterController()//constructor para inicializar
        {
            _CensosMasterBL = new CensoMaestroBL();//inicializando variable _CensosMasterBL

            _PeriodoBL = new PeriodoBL();

            _AlumnoBL = new AlumnoBL();
        }
        // GET: CensoMaster
        public ActionResult Index()
        {
            var listadeCenso = _CensosMasterBL.ObtenerCensos();

            return View(listadeCenso);
        }

        public ActionResult Crear()
        {
            var nuevoCenso = new CensoMaestro();

            var periodos = _PeriodoBL.ObtenerPeriodosActivos();

            var alumnos = _AlumnoBL.ObtenerAlumnosActivos();


            ViewBag.PeriodoId = new SelectList(periodos, "Id", "numero");

            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "NombreAlumno");


            return View(nuevoCenso);
        }

        [HttpPost]
        public ActionResult Crear(CensoMaestro censo)
        {
            if (ModelState.IsValid)
            {
                _CensosMasterBL.GuardarCenso(censo);

                return RedirectToAction("Index");
            }

            return View(censo);
        }


        public ActionResult Editar(int id)
        {
            var censo = _CensosMasterBL.ObtenerCensoDetalle(id);

            return View(censo);
        }

        [HttpPost]
        public ActionResult Editar(CensoMaestro censo)
        {
            if (ModelState.IsValid)
            {
                _CensosMasterBL.GuardarCenso(censo);

                return RedirectToAction("Index");
            }

            return View(censo);
        }


    }
}

censocademico/CargaAcademica.WebAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargaAcademica.WebAdmin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

censocademico/CargaAcademica.WebAdmin/Controllers/HorarioController.cs
using CargaAcademica.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargaAcademica.WebAdmin.Controllers
{
    public class HorarioController : Controller
    {
        HorariosBL _HorarioBL;

        public HorarioController()
        {
            _HorarioBL = new HorariosBL();
        }


        // GET: Horario
        public ActionResult Index()
        {
            var ListadeHorarios = _HorarioBL.ObtenerHorarios();

            return View(ListadeHorarios);
        }

        public ActionResult Crear()
        {
            var nuevoHorario = new Horarios();

            return View(nuevoHorario);
        }

        [HttpPost]//validacion
        public ActionResult Crear(Horarios horarios)
        {
            if (ModelState.IsValid)//validacion con estructura if que evalua si el model state es valio.
                                   //entonces permite guardar. 
            {
                

                _HorarioBL.GuardarHorario(horarios);


                return RedirectToAction("Index");
            }


            return View(horarios);
        }
        public ActionResult Editar(int Id)
        {
            var hora = _HorarioBL.ObtenerHorarios(Id);

            return View(hora);
        }

        [HttpPost]
        public ActionResult Editar(Horarios horarios)
        {
            if (ModelState.IsValid)
            {
               
                    
                _HorarioBL.GuardarHorario(horarios);

                return RedirectToAction("Index");//pendiente index tambien
            }

            return View(horarios);
        }


        public ActionResult Detalle(int Id)
        {
            var horarios = _HorarioBL.ObtenerHorarios(Id);

            return View(horarios);
        }

        [HttpPost]
        public ActionResult Eliminar(Horarios horarios)
        {
            _HorarioBL.EliminarHorario(horarios.Id);

            return RedirectToAction("Index");//pendiente index
        }


    }
}

censocademico/CargaAcademica.WebAdmin/Controllers/asignaturasController.cs
using CargaAcademica.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargaAcademica.WebAdmin.Controllers
{
    public class AsignaturasController : Controller
    {
        AsignaturasBL _asignaturasBL;

        public AsignaturasController()
        {
            _asignaturasBL = new AsignaturasBL();
        }

        // GET: Asignaturas
        public ActionResult Index()
        {
            var listadeAsignaturas = _asignaturasBL.ObtenerAsignaturas();

            return View(listadeAsignaturas);
        }

        public ActionResult Crear()
        {
            var nuevaAsignatura = new Asignatura();

            return View(nuevaAsignatura);
        }

        [HttpPost]
        public ActionResult Crear(Asignatura asignatura)
        {
            if (ModelState.IsValid)
            {
                _asignaturasBL.GuardarAsignatura(asignatura);

                return RedirectToAction("Index");
            }

            return View(asignatura);
        }

        public ActionResult Editar(int id)
        {
            var asignatura = _asignaturasBL.ObtenerAsignatura(id);

            return View(asignatura);
        }

        [HttpPost]
        public ActionResult Editar(Asignatura asignatura)
        {
            if (ModelState.IsValid)
            {
                _asignaturasBL.GuardarAsignatura(asignatura);

                return RedirectToAction("Index");
            }

            return View(asignatura);
        }

        public ActionResult Detalle(int id)
        {
            var asignatura = _asignaturasBL.ObtenerAsignatura(id);

            return View(asignatura);
        }

        public ActionResult Eliminar(int id)
        {
            var asignatura = _asignaturasBL.ObtenerAsignatura(id);

            return View(asignatura);
        }

        [HttpPost]
        public ActionResult Eliminar(Asignatura asignatura)
        {
            _asignaturasBL.EliminarAsignatura(asignatura.Id);

            return RedirectToAction("Index");
        }
    }
}

censocademico/CargaAcademica.WebAdmin/Views/Alumno/Crear.cshtml
@model CargaAcademica.BL.Alumno

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm("Crear","Alumno", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NombreAlumno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreAlumno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreAlumno, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "" } })
                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
            </div>

            
        </div>

       

        <div class="form-group">

            <label class="control-label col-md-2">Seleccione una imagen</label>
            <div class="control-label col-md-2">
                <input type="file" name="imagen" id="imagen" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regrese a la lista", "Index")
</div>

censocademico/CargaAcademica.WebAdmin/Views/CensoMaster/Crear.cshtml
@model CargaAcademica.BL.CensoMaestro

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CensoMaestro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PeriodoId, "PeriodoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PeriodoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PeriodoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlumnoId, "AlumnoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlumnoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlumnoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

censocademico/CargaAcademica.WebAdmin/Views/CensoMaster/Editar.cshtml
@model CargaAcademica.BL.CensoMaestro

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CensoMaestro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodoId, "PeriodoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PeriodoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PeriodoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlumnoId, "AlumnoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlumnoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlumnoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

censocademico/CargaAcademica.WebAdmin/Views/CensoMaster/Index.cshtml
@model IEnumerable<CargaAcademica.BL.CensoMaestro>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Censos</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Alumno.NombreAlumno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Periodo.numero)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Alumno.NombreAlumno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Periodo.año) - @Html.DisplayFor(modelItem => item.Periodo.numero)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Ver Asignatura", "Index","CensoDetalle", new { id=item.Id },null)
        </td>
    </tr>
}

</table>

censocademico/CargaAcademica.WebAdmin/Views/Horario/Crear.cshtml
@model CargaAcademica.BL.Horarios

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Horarios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

censocademico/CargaAcademica.WebAdmin/Views/Horario/Editar.cshtml
@model CargaAcademica.BL.Horarios

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Horarios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

censocademico/CargaAcademica.WebAdmin/Views/Horario/Eliminar.cshtml
@model CargaAcademica.BL.Horarios

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Horarios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

censocademico/CargaAcademica.WebAdmin/Views/Horario/Index.cshtml
@model IEnumerable<CargaAcademica.BL.Horarios>

@{
    ViewBag.Title = "Horarios";
}

<h2>Horarios</h2>

<p>
    @Html.ActionLink("Crear nuevo horario", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Horario)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Elinar", new { id=item.Id })
        </td>
    </tr>
}

</table>

censocademico/CargaAcademica.WebAdmin/Views/Periodos/Editar.cshtml
@model CargaAcademica.BL.Periodo

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Periodo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.año, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.año, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

censocademico/CargaAcademica.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Todos los derechos reservados</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Informatica Administrativa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("inicio","Index","Home")
                    </li>
                    <li>
                        @Html.ActionLink("Asignaturas", "Index", "Asignaturas")

                    </li>
                    <li>
                    @Html.ActionLink("Horario", "Index", "Horario")
                    </li>
                    <li>
                        @Html.ActionLink("Periodos", "Index", "Periodos")
                    </li>
                    <li>
                        @Html.ActionLink("Alumno", "Index", "Alumno")
                    </li>
                    <li>
                        @Html.ActionLink("CensoDetalle", "Index", "CensoDetalle")
                    </li>
                    <li>
                        @Html.ActionLink("Censo", "Index", "CensoMaster")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Censo Informatica Administrativa</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>